=== venables/credential-manifest/test/credential-manifest/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "required": [
    "issuer",
    "output_descriptors"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "issuer": {
      "type": "object",
      "required": [
        "id",
        "name",
        "styles"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "styles": {
          "type": "object",
          "required": [],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "output_descriptors": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "anyOf": [
          {
            "type": "object",
            "required": [
              "schema",
              "display",
              "styles"
            ],
            "properties": {
              "schema": {
                "type": "array",
                "additionalItems": false,
                "items": {
                  "anyOf": [
                    {
                      "type": "object",
                      "required": [
                        "uri"
                      ],
                      "properties": {
                        "uri": {
                          "type": "string"
                        }
                      },
                      "additionalProperties": false
                    }
                  ]
                }
              },
              "display": {
                "type": "object",
                "required": [
                  "title",
                  "subtitle",
                  "description",
                  "properties"
                ],
                "properties": {
                  "title": {
                    "type": "object",
                    "required": [
                      "path",
                      "fallback"
                    ],
                    "properties": {
                      "path": {
                        "type": "array",
                        "additionalItems": false,
                        "items": {
                          "anyOf": [
                            {
                              "type": "string"
                            }
                          ]
                        }
                      },
                      "fallback": {
                        "type": "string"
                      }
                    },
                    "additionalProperties": false
                  },
                  "subtitle": {
                    "type": "object",
                    "required": [
                      "path",
                      "fallback"
                    ],
                    "properties": {
                      "path": {
                        "type": "array",
                        "additionalItems": false,
                        "items": {
                          "anyOf": [
                            {
                              "type": "string"
                            }
                          ]
                        }
                      },
                      "fallback": {
                        "type": "string"
                      }
                    },
                    "additionalProperties": false
                  },
                  "description": {
                    "type": "object",
                    "required": [
                      "text"
                    ],
                    "properties": {
                      "text": {
                        "type": "string"
                      }
                    },
                    "additionalProperties": false
                  },
                  "properties": {
                    "type": "array",
                    "additionalItems": false,
                    "items": {
                      "anyOf": [
                        {
                          "type": "object",
                          "required": [
                            "path",
                            "fallback",
                            "label"
                          ],
                          "properties": {
                            "path": {
                              "type": "array",
                              "additionalItems": false,
                              "items": {
                                "anyOf": [
                                  {
                                    "type": "string"
                                  }
                                ]
                              }
                            },
                            "fallback": {
                              "type": "string"
                            },
                            "label": {
                              "type": "string"
                            }
                          },
                          "additionalProperties": false
                        }
                      ]
                    }
                  }
                },
                "additionalProperties": false
              },
              "styles": {
                "type": "object",
                "required": [],
                "additionalProperties": false
              }
            },
            "additionalProperties": false
          }
        ]
      }
    },
    "presentation_definition": {
      "type": "object",
      "required": [],
      "additionalProperties": false
    },
    "format": {}
  },
  "additionalProperties": false
}

=== venables/credential-manifest/test/credential-manifest/all_features.json
{
  "id": "WA-DL-CLASS-A",
  "version": "0.1.0",
  "issuer": {
    "id": "did:example:123?linked-domains=3",
    "name": "Washington State Government",
    "styles": {}
  },
  "output_descriptors": [
    {
      "schema": [
        {
          "uri": "http://washington-state-schemas.org/1.0.0/driver-license.json"
        }
      ],
      "display": {
        "title": {
          "path": [
            "$.name",
            "$.vc.name"
          ],
          "fallback": "Washington State Driver License"
        },
        "subtitle": {
          "path": [
            "$.class",
            "$.vc.class"
          ],
          "fallback": "Class A, Commercial"
        },
        "description": {
          "text": "License to operate a vehicle with a gross combined weight rating (GCWR) of 26,001 or more pounds, as long as the GVWR of the vehicle(s) being towed is over 10,000 pounds."
        },
        "properties": [
          {
            "path": [
              "$.donor",
              "$.vc.donor"
            ],
            "fallback": "Unknown",
            "label": "Organ Donor"
          }
        ]
      },
      "styles": {}
    }
  ],
  "presentation_definition": {}
}
